// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj5NosXDEKBhPp_FcFbjeW81kFatF_8ak',
    appId: '1:749813796442:web:00703870b8c8e03d3d1263',
    messagingSenderId: '749813796442',
    projectId: 'todo-20app',
    authDomain: 'todo-20app.firebaseapp.com',
    storageBucket: 'todo-20app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSIncMlyR1Ei_ZyDUskw9jKbcNZ3Eq4ms',
    appId: '1:749813796442:android:d51733e19661cd903d1263',
    messagingSenderId: '749813796442',
    projectId: 'todo-20app',
    storageBucket: 'todo-20app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ02pVXbIvqcHzm4JUheCcSZ9knSlEXvs',
    appId: '1:749813796442:ios:d1b30dbc8f601e903d1263',
    messagingSenderId: '749813796442',
    projectId: 'todo-20app',
    storageBucket: 'todo-20app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ02pVXbIvqcHzm4JUheCcSZ9knSlEXvs',
    appId: '1:749813796442:ios:d1b30dbc8f601e903d1263',
    messagingSenderId: '749813796442',
    projectId: 'todo-20app',
    storageBucket: 'todo-20app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj5NosXDEKBhPp_FcFbjeW81kFatF_8ak',
    appId: '1:749813796442:web:97d05d01cf4b50ed3d1263',
    messagingSenderId: '749813796442',
    projectId: 'todo-20app',
    authDomain: 'todo-20app.firebaseapp.com',
    storageBucket: 'todo-20app.firebasestorage.app',
  );
}
